// ============================================================
// ClaimPilot AI — Mock Data for Development
// Swap these with real API calls when backend is live
// ============================================================

import type { ClaimDetail, ClaimRecord, ManualReviewItem } from './types';

export const MOCK_CLAIMS: ClaimRecord[] = [
  {
    claim_id: 'CLM-2024-001',
    member_id: 'MBR-001',
    member_name: 'Rahul Sharma',
    treatment_date: '2024-12-10',
    claim_amount: 3500,
    hospital: 'Apollo Hospital, Bangalore',
    cashless_request: false,
    decision: 'APPROVED',
    approved_amount: 3150,
    confidence_score: 0.95,
    created_at: '2024-12-10T10:30:00Z',
  },
  {
    claim_id: 'CLM-2024-002',
    member_id: 'MBR-002',
    member_name: 'Priya Mehta',
    treatment_date: '2024-12-11',
    claim_amount: 8000,
    hospital: 'Fortis Healthcare',
    cashless_request: true,
    decision: 'REJECTED',
    approved_amount: 0,
    confidence_score: 0.96,
    created_at: '2024-12-11T14:00:00Z',
  },
  {
    claim_id: 'CLM-2024-003',
    member_id: 'MBR-003',
    member_name: 'Arun Kumar',
    treatment_date: '2024-12-12',
    claim_amount: 4200,
    hospital: 'Manipal Hospitals',
    cashless_request: false,
    decision: 'PARTIAL',
    approved_amount: 3000,
    confidence_score: 0.92,
    created_at: '2024-12-12T09:15:00Z',
  },
  {
    claim_id: 'CLM-2024-004',
    member_id: 'MBR-004',
    member_name: 'Sunita Patel',
    treatment_date: '2024-12-13',
    claim_amount: 12000,
    hospital: 'Max Healthcare',
    cashless_request: false,
    decision: 'MANUAL_REVIEW',
    approved_amount: 0,
    confidence_score: 0.65,
    created_at: '2024-12-13T16:45:00Z',
  },
  {
    claim_id: 'CLM-2024-005',
    member_id: 'MBR-005',
    member_name: 'Vikram Singh',
    treatment_date: '2024-12-14',
    claim_amount: 2800,
    hospital: 'Narayana Health',
    cashless_request: false,
    decision: 'APPROVED',
    approved_amount: 2520,
    confidence_score: 0.93,
    created_at: '2024-12-14T11:20:00Z',
  },
];

export const MOCK_CLAIM_DETAILS: Record<string, ClaimDetail> = {
  'CLM-2024-001': {
    claim_id: 'CLM-2024-001',
    member_id: 'MBR-001',
    member_name: 'Rahul Sharma',
    treatment_date: '2024-12-10',
    claim_amount: 3500,
    hospital: 'Apollo Hospital, Bangalore',
    cashless_request: false,
    decision: 'APPROVED',
    approved_amount: 3150,
    confidence_score: 0.95,
    created_at: '2024-12-10T10:30:00Z',
    result: {
      claim_id: 'CLM-2024-001',
      decision: 'APPROVED',
      approved_amount: 3150,
      confidence_score: 0.95,
      fraud_score: 0.05,
      rejection_reasons: [],
      rejected_items: [],
      flags: [],
      notes: null,
      next_steps: 'Reimbursement will be processed within 5-7 working days.',
      deductions: { copay: 350 },
      network_discount: null,
      cashless_approved: null,
      evidence: [
        { rule: 'Policy Active Check', status: 'passed', details: 'Policy is active. Member joined 2024-06-01.' },
        { rule: 'Waiting Period Validation', status: 'passed', details: 'No waiting period applies to this condition.' },
        { rule: 'Document Validation', status: 'passed', details: 'Prescription and medical bill are present and valid.' },
        { rule: 'Doctor Registration Check', status: 'passed', details: 'Dr. Suresh Kumar is registered: KA/45678/2015.' },
        { rule: 'Coverage Check', status: 'passed', details: 'Consultation is a covered OPD service.' },
        { rule: 'Exclusion Check', status: 'passed', details: 'No excluded services found in claim.' },
        { rule: 'Per-Claim Limit Check', status: 'passed', details: 'Claim ₹3500 is within the ₹5000 per-claim limit.' },
        { rule: 'Copay Calculation', status: 'passed', details: '10% copay applied: ₹350 deducted.' },
        { rule: 'Fraud Detection', status: 'passed', details: 'No suspicious patterns detected.' },
      ],
    },
    documents: [
      { document_id: 'DOC-001', claim_id: 'CLM-2024-001', document_type: 'PRESCRIPTION', classification_confidence: 0.97, created_at: '2024-12-10T10:28:00Z' },
      { document_id: 'DOC-002', claim_id: 'CLM-2024-001', document_type: 'MEDICAL_BILL', classification_confidence: 0.99, created_at: '2024-12-10T10:29:00Z' },
    ],
    audit_logs: [
      { id: 1, claim_id: 'CLM-2024-001', action: 'CLAIM_SUBMITTED', details: { channel: 'web_portal' }, created_at: '2024-12-10T10:30:00Z' },
      { id: 2, claim_id: 'CLM-2024-001', action: 'EXTRACTION_COMPLETED', details: { documents: 2, confidence: 0.98 }, created_at: '2024-12-10T10:30:45Z' },
      { id: 3, claim_id: 'CLM-2024-001', action: 'ADJUDICATION_COMPLETED', details: { decision: 'APPROVED', engine_version: '1.0' }, created_at: '2024-12-10T10:31:02Z' },
    ],
    manual_review: null,
  },
  'CLM-2024-002': {
    claim_id: 'CLM-2024-002',
    member_id: 'MBR-002',
    member_name: 'Priya Mehta',
    treatment_date: '2024-12-11',
    claim_amount: 8000,
    hospital: 'Fortis Healthcare',
    cashless_request: true,
    decision: 'REJECTED',
    approved_amount: 0,
    confidence_score: 0.96,
    created_at: '2024-12-11T14:00:00Z',
    result: {
      claim_id: 'CLM-2024-002',
      decision: 'REJECTED',
      approved_amount: 0,
      confidence_score: 0.96,
      fraud_score: 0.1,
      rejection_reasons: ['WAITING_PERIOD'],
      rejected_items: [],
      flags: [],
      notes: 'Diabetes has 90-day waiting period. Eligible from 2024-11-30.',
      next_steps: 'Resubmit the claim after the waiting period expires.',
      deductions: null,
      network_discount: null,
      cashless_approved: false,
      evidence: [
        { rule: 'Policy Active Check', status: 'passed', details: 'Policy is active.' },
        { rule: 'Waiting Period Validation', status: 'failed', details: 'Diabetes treatment has a 90-day waiting period. Treatment date falls within the waiting window.' },
        { rule: 'Document Validation', status: 'skipped', details: 'Skipped due to hard rejection.' },
        { rule: 'Coverage Check', status: 'skipped', details: 'Skipped due to hard rejection.' },
      ],
    },
    documents: [
      { document_id: 'DOC-003', claim_id: 'CLM-2024-002', document_type: 'PRESCRIPTION', classification_confidence: 0.96, created_at: '2024-12-11T13:58:00Z' },
    ],
    audit_logs: [
      { id: 4, claim_id: 'CLM-2024-002', action: 'CLAIM_SUBMITTED', details: { channel: 'web_portal' }, created_at: '2024-12-11T14:00:00Z' },
      { id: 5, claim_id: 'CLM-2024-002', action: 'ADJUDICATION_COMPLETED', details: { decision: 'REJECTED', reason: 'WAITING_PERIOD' }, created_at: '2024-12-11T14:01:10Z' },
    ],
    manual_review: null,
  },
  'CLM-2024-003': {
    claim_id: 'CLM-2024-003',
    member_id: 'MBR-003',
    member_name: 'Arun Kumar',
    treatment_date: '2024-12-12',
    claim_amount: 4200,
    hospital: 'Manipal Hospitals',
    cashless_request: false,
    decision: 'PARTIAL',
    approved_amount: 3000,
    confidence_score: 0.92,
    created_at: '2024-12-12T09:15:00Z',
    result: {
      claim_id: 'CLM-2024-003',
      decision: 'PARTIAL',
      approved_amount: 3000,
      confidence_score: 0.92,
      fraud_score: 0.08,
      rejection_reasons: [],
      rejected_items: ['root_canal'],
      flags: [],
      notes: 'Dental sub-limit of ₹3000 applied. Root canal partially covered.',
      next_steps: 'Approved portion will be processed. Remaining ₹1200 is patient liability.',
      deductions: { copay: 300 },
      network_discount: null,
      cashless_approved: null,
      evidence: [
        { rule: 'Policy Active Check', status: 'passed', details: 'Policy is active.' },
        { rule: 'Coverage Check', status: 'passed', details: 'Dental treatment is covered with a sub-limit.' },
        { rule: 'Dental Sub-Limit Check', status: 'failed', details: 'Claim ₹4200 exceeds dental sub-limit of ₹3000. Partial approval applied.' },
        { rule: 'Fraud Detection', status: 'passed', details: 'No suspicious patterns detected.' },
      ],
    },
    documents: [
      { document_id: 'DOC-005', claim_id: 'CLM-2024-003', document_type: 'MEDICAL_BILL', classification_confidence: 0.98, created_at: '2024-12-12T09:12:00Z' },
      { document_id: 'DOC-006', claim_id: 'CLM-2024-003', document_type: 'PRESCRIPTION', classification_confidence: 0.95, created_at: '2024-12-12T09:13:00Z' },
    ],
    audit_logs: [
      { id: 6, claim_id: 'CLM-2024-003', action: 'CLAIM_SUBMITTED', details: {}, created_at: '2024-12-12T09:15:00Z' },
      { id: 7, claim_id: 'CLM-2024-003', action: 'ADJUDICATION_COMPLETED', details: { decision: 'PARTIAL', approved: 3000 }, created_at: '2024-12-12T09:15:52Z' },
    ],
    manual_review: null,
  },
  'CLM-2024-004': {
    claim_id: 'CLM-2024-004',
    member_id: 'MBR-004',
    member_name: 'Sunita Patel',
    treatment_date: '2024-12-13',
    claim_amount: 12000,
    hospital: 'Max Healthcare',
    cashless_request: false,
    decision: 'MANUAL_REVIEW',
    approved_amount: 0,
    confidence_score: 0.65,
    created_at: '2024-12-13T16:45:00Z',
    result: {
      claim_id: 'CLM-2024-004',
      decision: 'MANUAL_REVIEW',
      approved_amount: 0,
      confidence_score: 0.65,
      fraud_score: 0.72,
      rejection_reasons: [],
      rejected_items: [],
      flags: ['DUPLICATE_CLAIM_SAME_DAY', 'HIGH_AMOUNT_ANOMALY'],
      notes: 'Claim flagged for manual review due to potential fraud indicators.',
      next_steps: 'Assigned to Claims Analyst for manual verification.',
      deductions: null,
      network_discount: null,
      cashless_approved: null,
      evidence: [
        { rule: 'Policy Active Check', status: 'passed', details: 'Policy is active.' },
        { rule: 'Duplicate Claim Detection', status: 'failed', details: 'A claim from the same member was submitted on the same treatment date.' },
        { rule: 'Amount Anomaly Check', status: 'failed', details: 'Claim amount ₹12,000 is significantly higher than member average (₹3,200).' },
        { rule: 'Fraud Score Calculation', status: 'failed', details: 'Composite fraud score 0.72 exceeds threshold of 0.5.' },
      ],
    },
    documents: [
      { document_id: 'DOC-007', claim_id: 'CLM-2024-004', document_type: 'MEDICAL_BILL', classification_confidence: 0.88, created_at: '2024-12-13T16:43:00Z' },
    ],
    audit_logs: [
      { id: 8, claim_id: 'CLM-2024-004', action: 'CLAIM_SUBMITTED', details: {}, created_at: '2024-12-13T16:45:00Z' },
      { id: 9, claim_id: 'CLM-2024-004', action: 'FRAUD_FLAGS_RAISED', details: { flags: ['DUPLICATE_CLAIM_SAME_DAY', 'HIGH_AMOUNT_ANOMALY'] }, created_at: '2024-12-13T16:45:30Z' },
      { id: 10, claim_id: 'CLM-2024-004', action: 'ESCALATED_TO_MANUAL_REVIEW', details: { fraud_score: 0.72 }, created_at: '2024-12-13T16:45:31Z' },
    ],
    manual_review: {
      claim_id: 'CLM-2024-004',
      member_name: 'Sunita Patel',
      claim_amount: 12000,
      flags: ['DUPLICATE_CLAIM_SAME_DAY', 'HIGH_AMOUNT_ANOMALY'],
      confidence_score: 0.65,
      created_at: '2024-12-13T16:45:00Z',
      reviewed_at: null,
      final_decision: null,
    },
  },
};

export const MOCK_MANUAL_REVIEW_QUEUE: ManualReviewItem[] = [
  {
    claim_id: 'CLM-2024-004',
    member_name: 'Sunita Patel',
    claim_amount: 12000,
    flags: ['DUPLICATE_CLAIM_SAME_DAY', 'HIGH_AMOUNT_ANOMALY'],
    confidence_score: 0.65,
    created_at: '2024-12-13T16:45:00Z',
    reviewed_at: null,
    final_decision: null,
  },
  {
    claim_id: 'CLM-2024-006',
    member_name: 'Deepak Joshi',
    claim_amount: 9500,
    flags: ['UNREGISTERED_DOCTOR'],
    confidence_score: 0.71,
    created_at: '2024-12-14T08:20:00Z',
    reviewed_at: null,
    final_decision: null,
  },
  {
    claim_id: 'CLM-2024-007',
    member_name: 'Kavitha Reddy',
    claim_amount: 6700,
    flags: ['DUPLICATE_CLAIM_SAME_DAY'],
    confidence_score: 0.68,
    created_at: '2024-12-14T12:00:00Z',
    reviewed_at: '2024-12-14T15:30:00Z',
    final_decision: 'REJECTED',
  },
];
